### ISSUE TITLE
Move settings into the "Configure" button w/ field formatter settings

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_wrappers#2]
The Drupal 7 version of this module adds the Wrapper selects in a rather unsightly way:

![screen shot 2019-01-29 at 12 39 57 pm](https://user-images.githubusercontent.com/871421/51931655-03bfb100-23c3-11e9-8111-eaa1c7e55c16.jpg)

I've made modifications that I think are better (single column fieldset, collapsed by default):

![screen shot 2019-01-29 at 12 41 08 pm](https://user-images.githubusercontent.com/871421/51931729-2baf1480-23c3-11e9-85f8-5f67cc00e687.jpg)

But I think the ideal would be to get a fieldset inserted into the "Configure" button that shows up on some fields, and create a "Configure" button for fields that don't have one. 

Do you agree? Is that even possible? Anybody have some tips?

**Comment by opi** [comment]
+1 on having a fieldset into the Configure form (and to create this configure form if not present).

I can have a look tomorrow, but afaik, extending formatter in D7 require the https://www.drupal.org/project/field_formatter_settings by Dave Reid. Source : https://www.drupal.org/node/2130757 ; What about having field_formatter_settings in core ? it's a very short and useful module, allowing other contrib to extend the field/formatter API.

**Comment by laryn** [comment]
@opi Ha, I forgot I ported that one at one point because another module needed it. https://github.com/backdrop-contrib/field_formatter_settings

I guess I can investigate whether that will make it simpler to do, and make a dependency if we can't get `field_formatter_settings` in core.

**Comment by opi** [comment]
oh, didn't even look for field_formatter_settings to be ported ; Maybe as a start you could have it as a dependency for field_wrappers ? I guess the "field_formatter_settings in core" should be another issue

**Comment by klonos** [comment]
I like the way this is implemented in D7 because it provides a quick overview + it allows setting those without any additional clicking. Having said that, I realise that multiple columns means that it requires more horizontal space, and that this might become an issue on smaller-sized devices.

The single-column, fieldset implementation is not bad, but it does require additional clicks to show/hide the drop-down menus (when you want to either change settings or get an overview of the current ones). Although admittedly, this will work better on narrower screens.

AFAIK, the "standard" way in Drupal is to have the configure button expand the table row as if it was a fieldset, and then have all widget/field settings live there, with some sort of "Update settings" button. Here's a screenshot from https://github.com/backdrop/backdrop-issues/issues/1032#issuecomment-435414532:

![screen shot 2018-11-03 at 2 33 49 am](https://user-images.githubusercontent.com/2423362/47924892-f6547100-df10-11e8-9d3b-2e78716d6ceb.png)

I would love to get this + field_formatter_settings in core. We already have an issue about this (filed by yours truly back in 2015 😄): https://github.com/backdrop/backdrop-issues/issues/1376

**Comment by laryn** [comment]
@opi @klonos @olafgrabienski 
I pushed a new branch with a dependency on `field_formatter_settings`. Let me know what you think if you test it out.


![screen shot 2019-01-29 at 10 45 18 pm](https://user-images.githubusercontent.com/871421/51959063-6b541b80-2418-11e9-9cfa-1a0e382fae86.jpg)


![screen shot 2019-01-29 at 10 45 31 pm](https://user-images.githubusercontent.com/871421/51959070-71e29300-2418-11e9-8759-40ad10010cee.jpg)
